name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  VERSION: $(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set tag
      id: tag
      run: echo "tag=$(date +'%Y%m%d')_$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag blog:$TAG_NAME
      env:
          TAG_NAME: ${{ steps.tag.outputs.tag }}
    - name: Push the Docker image
      run: echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ secrets.USER }} --password-stdin && docker push ghcr.io/agh92/blog:$TAG_NAME
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} |
        TAG_NAME: ${{ steps.tag.outputs.tag }}
